Use ONTHEFLAY

CREATE DATABASE ONTHEFLAY;

CREATE TABLE PASSAGEIRO(

CPF varchar (11) NOT NULL,
NOME varchar (50) NOT NULL,
DATA_NASCIMENTO date NOT NULL,
DATA_CADASTRO date NOT NULL,
SEXO  char (1),
SITUACAO char(1),
ULTIMA_COMPRA date,

CONSTRAINT PK_CPF_PASSAGEIRO PRIMARY KEY (CPF));

CREATE TABLE COMPANHIA_AEREA(

CNPJ varchar (14) NOT NULL,
DATA_ABERTURA datetime NOT NULL,
ULTIMO_VOO datetime,
SITUACAO char,
DATA_CADASTRO datetime NOT NULL,
RAZAO_SOCIAL varchar(50),

CONSTRAINT PK_CNPJ_COMPANHIA_AEREA PRIMARY KEY (CNPJ));



CREATE TABLE PASSAGENS(

ID varchar(6) NOT NULL,
ID_VOO varchar(5) NOT NULL,
DATA_ULTIMA_OPERACAO date NOT NULL,
VALOR float,
SITUACAO char(1),

CONSTRAINT PK_ID_PASSAGENS PRIMARY KEY (ID),
FOREIGN KEY(ID_VOO) REFERENCES VOO(ID));

CREATE TABLE AERONAVE(

ID_ANAC varchar (6) NOT NULL,
CNPJ varchar(14)NOT NULL,
DATA_CADASTRO date NOT NULL,
SITUACAO char(10),
ULTIMA_VENDA date,
CAPACIDADE int,

CONSTRAINT PK_ID_AERONAVE PRIMARY KEY (ID_ANAC),
FOREIGN KEY(CNPJ) REFERENCES COMPANHIA_AEREA(CNPJ));

CREATE TABLE VOO(

ID varchar(5) NOT NULL,
ID_ANAC VARCHAR (6) NOT NULL,
ASSENTOS_OCUPADOS int,
DATA_CADASTRO date NOT NULL,
SITUACAO char(1),
DATA_VOO date,
DESTINO varchar(25),

CONSTRAINT PK_ID_VOOO PRIMARY KEY (ID),
FOREIGN KEY(ID_ANAC) REFERENCES AERONAVE(ID_ANAC));

create table PASSAGEMVENDA( 
	Id int not null, 
	DataVenda date not null, 
	ValorTotal float not null, 
	IDItemVenda varchar(6), 
	Passageiro varchar(11) not null, 
    ValorUnitario float,	
	Voo varchar(5) not null, 
	
	constraint PK_ID_PASSAGEMVENDA primary key (Id),
	FOREIGN KEY(Voo) REFERENCES VOO(ID),
	FOREIGN KEY(Passageiro) REFERENCES PASSAGEIRO(CPF));
	
	create table VENDAPASSAGEIRO( 
	Id int identity not null,
	DataVenda date,
	CPF varchar(11),
	ValorTotal float,
	constraint PK_ID_VENDAPASSAGEIRO primary key (Id),
	foreign key (CPF) references Passageiro(CPF));


CREATE TABLE RESTRITO(
CPF varchar(11) nOT NULL,
CONSTRAINT PK_ID_RESTRITO PRIMARY KEY (CPF));

CREATE TABLE BLOQUEADO(
CNPJ varchar (14) NOT NULL,
CONSTRAINT PK_ID_BLOQUEADO PRIMARY KEY (CNPJ));

